services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
  reservations:
    image: reservations
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: auth
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: payments
    ports:
      - '3003:3003'
    env_file:
      - ../apps/payments/.env
  notifications:
    image: notifications
    ports:
      - '3004:3004'
    env_file:
      - ../apps/notifications/.env